### PR TITLE
Nimble Python SDK modules, setup and README files

### PR DESCRIPTION
**Pull request by suneeth51**

### CODE REVIEW

**Review by rgcostea — APPROVED** [review]
Looks great.

**Review by nimblesorge — COMMENTED** [review]
Looks good! My only suggestion is to add the parameter type to docstrings. So:
id : Identifier for the access control record.
becomes
id (NSObjectId) : Identifier for the access control record.

**Comment by rgcostea** [comment]
> Looks good! My only suggestion is to add the parameter type to docstrings. So:
> id : Identifier for the access control record.
> becomes
> id (NSObjectId) : Identifier for the access control record.

But an NsObjectId is really a string at the end of the day.  Shouldn't we just deal with a string rather than a wrapper type?

**Comment by nimblesorge** [comment]
It seems to me that using the Nimble (wrapper) types will be clearer in the long run as they often carry restrictions that, say, a Python string doesn't. My (perhaps outdated) documentation indicates that a NSObjectId is not just a string, but rather, "A 42 digit hexadecimal number", for instance. So, providing the Nimble type, rather than the base type forces the user to be aware of any such restrictions that might exist.

But, my larger point was just that types would be helpful. Both "id (string)" and "id (NSObjectId)" provide more  information to the user than just "id".

**Comment by rgcostea** [comment]
Yes, it's a 42 digit hexadecimal number but its json-type is a string.  I think part of the purpose of having the SDK is to eliminate this type of complexity.  When it matters, we should expose it.  When it doesn't, we should strive to keep it simple.

**Pull request merged**
