### PR TITLE
Package versioning

### PR DESCRIPTION
**Pull request by ghost**
Added new version file.
Added new logic to set versions from the version file on the pypi package.

### CODE REVIEW

**Comment by ghost** [comment]
Testing:
```
$ cat nimbleclient/_version.py 
# This file is protected via CODEOWNERS
__version__ = "1.0.0"

$ python3.6 setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/nimbleclient
copying nimbleclient/__init__.py -> build/lib/nimbleclient
copying nimbleclient/_version.py -> build/lib/nimbleclient
creating build/lib/nimbleclient/v1
copying nimbleclient/v1/__init__.py -> build/lib/nimbleclient/v1
copying nimbleclient/v1/client.py -> build/lib/nimbleclient/v1
copying nimbleclient/v1/exceptions.py -> build/lib/nimbleclient/v1
copying nimbleclient/v1/resource.py -> build/lib/nimbleclient/v1
copying nimbleclient/v1/restclient.py -> build/lib/nimbleclient/v1
creating build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/__init__.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/access_control_records.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/active_directory_memberships.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/alarms.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/application_categories.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/application_servers.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/arrays.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/audit_log.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/chap_users.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/controllers.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/disks.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/events.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/fibre_channel_configs.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/fibre_channel_initiator_aliases.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/fibre_channel_interfaces.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/fibre_channel_ports.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/fibre_channel_sessions.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/folders.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/groups.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/initiator_groups.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/initiators.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/jobs.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/key_managers.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/master_key.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/network_configs.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/network_interfaces.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/performance_policies.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/pools.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/protection_schedules.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/protection_templates.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/protocol_endpoints.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/replication_partners.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/shelves.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/snapshot_collections.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/snapshots.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/software_versions.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/space_domains.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/subnets.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/tokens.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/user_groups.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/user_policies.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/users.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/versions.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/volume_collections.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/volumes.py -> build/lib/nimbleclient/v1/api
copying nimbleclient/v1/api/witnesses.py -> build/lib/nimbleclient/v1/api
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/nimbleclient
copying build/lib/nimbleclient/__init__.py -> build/bdist.linux-x86_64/wheel/nimbleclient
copying build/lib/nimbleclient/_version.py -> build/bdist.linux-x86_64/wheel/nimbleclient
creating build/bdist.linux-x86_64/wheel/nimbleclient/v1
copying build/lib/nimbleclient/v1/__init__.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1
copying build/lib/nimbleclient/v1/client.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1
copying build/lib/nimbleclient/v1/exceptions.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1
copying build/lib/nimbleclient/v1/resource.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1
copying build/lib/nimbleclient/v1/restclient.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1
creating build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/__init__.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/access_control_records.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/active_directory_memberships.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/alarms.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/application_categories.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/application_servers.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/arrays.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/audit_log.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/chap_users.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/controllers.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/disks.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/events.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/fibre_channel_configs.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/fibre_channel_initiator_aliases.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/fibre_channel_interfaces.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/fibre_channel_ports.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/fibre_channel_sessions.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/folders.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/groups.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/initiator_groups.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/initiators.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/jobs.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/key_managers.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/master_key.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/network_configs.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/network_interfaces.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/performance_policies.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/pools.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/protection_schedules.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/protection_templates.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/protocol_endpoints.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/replication_partners.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/shelves.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/snapshot_collections.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/snapshots.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/software_versions.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/space_domains.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/subnets.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/tokens.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/user_groups.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/user_policies.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/users.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/versions.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/volume_collections.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/volumes.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
copying build/lib/nimbleclient/v1/api/witnesses.py -> build/bdist.linux-x86_64/wheel/nimbleclient/v1/api
running install_egg_info
running egg_info
creating nimble_python_sdk.egg-info
writing nimble_python_sdk.egg-info/PKG-INFO
writing dependency_links to nimble_python_sdk.egg-info/dependency_links.txt
writing requirements to nimble_python_sdk.egg-info/requires.txt
writing top-level names to nimble_python_sdk.egg-info/top_level.txt
writing manifest file 'nimble_python_sdk.egg-info/SOURCES.txt'
reading manifest file 'nimble_python_sdk.egg-info/SOURCES.txt'
writing manifest file 'nimble_python_sdk.egg-info/SOURCES.txt'
Copying nimble_python_sdk.egg-info to build/bdist.linux-x86_64/wheel/nimble_python_sdk-1.0.0-py3.6.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/nimble_python_sdk-1.0.0.dist-info/WHEEL
$ 
```

**Review by suneeth51 — APPROVED** [review]
lgtm..

**Review by cristian-medina — CHANGES_REQUESTED** [review]
We should put `__version__` in `nimbleclient/__init__.py` that ties it into the built-in mechanisms.

**Comment by git4mandar** [comment]
> We should put `__version__` in `nimbleclient/__init__.py` that ties it into the built-in mechanisms.

Hi @cristian-medina ,
I like the idea of keeping package versions into its own separate namespace/file. But I do see some benefits in getting the version from the nimbleclient class. We can import the version into nimbleclient class and let everyone consume it from that namespace. What do you think?

**Comment by ghost** [comment]
Closing pull request to work on new implementation

**Pull request closed without merging**
